# Generated by Django 5.1.5 on 2025-10-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
