# Generated by Django 5.1.5 on 2025-11-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0002_site_created_at_site_name_site_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='project',
        ),
        migrations.RemoveField(
            model_name='site',
            name='site_manager',
        ),
        migrations.AddField(
            model_name='site',
            name='project_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
