# Generated by Django 5.1.5 on 2025-11-12 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0003_remove_site_project_remove_site_site_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('site', 'date')},
        ),
        migrations.AddField(
            model_name='dailylog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='work_done',
        ),
    ]
