# Generated by Django 5.1.5 on 2025-11-12 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0004_alter_dailylog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safetyrecord',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='safetyrecord',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='safetyrecord',
            name='reported_by',
        ),
        migrations.AddField(
            model_name='safetyrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='safetyrecord',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safetyrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='safetyrecord',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20),
        ),
    ]
